name: Plugin CI
on:
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  js-lint:
    name: JS Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check changed files
        id: 'js-files'
        uses: tj-actions/changed-files@v35.4.3
        with:
          files: |
            **/*.js
            **/*.json

      - name: Setup node
        if: steps.js-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Lint
        if: steps.js-files.outputs.any_changed == 'true'
        run: npm run lint:js

  php-lint:
    name: PHP Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check changed files
        id: 'php-files'
        uses: tj-actions/changed-files@v35.4.3
        with:
          files: |
            **/*.php

      - name: Setup PHP
        if: steps.php-files.outputs.any_changed == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Download deps
        if: steps.php-files.outputs.any_changed == 'true'
        uses: ramsey/composer-install@v2

      - name: Lint
        if: steps.php-files.outputs.any_changed == 'true'
        run: composer run-script lint
